spring:
  application:
    name: usuarios

server:
  port: ${SERVER_PORT}

logging:
  level:
    root: ${LOG_LEVEL_ROOT}
    'co.edu.unicauca.autenticacion.api': ${LOG_LEVEL_API}
  file:
    name: ${LOG_FILE_NAME}
    max-size: ${LOG_FILE_MAX_SIZE}
    max-history: ${LOG_FILE_MAX_HISTORY}
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"

google:
  client:
    id: ${GOOGLE_CLIENT_ID}
    secret: ${GOOGLE_CLIENT_SECRET}

app:
  jwtSecret: ${JWT_SECRET}
  jwtExpirationMs: 86400000

kira:
  api:
    url: http://localhost:8080/api/kira
